spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        druid:
            url: jdbc:h2:~/demo
            username: sa
            password:
            driverClassName: org.h2.Driver
            initialSize: 5  #初始建立连接数量
            minIdle: 5  #最小连接数量
            maxActive: 20 #最大连接数量
            maxWait: 10000  #获取连接最大等待时间，毫秒
            testOnBorrow: true #申请连接时检测连接是否有效
            testOnReturn: false #归还连接时检测连接是否有效
            timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
            minEvictableIdleTimeMillis: 300000 #连接在连接池的最小生存时间（毫秒）
    jpa:
        properties:
            hibernate:
                show_sql: true
        hibernate:
            ddl-auto: update

        jta:
            log-dir: classpath:jta-logs2
            transaction-manager-id: txManager

    h2:
        console:
            enabled: true
            path: /console
            settings:
                trace: false
                web-allow-others: true

    application:
        name: demo
    thymeleaf:
        cache: false

server:
    port: 80
