spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        url: jdbc:h2:~/test
        username: sa
        password:
        driverClassName: org.h2.Driver

    jpa:
        properties:
            hibernate:
                show_sql: true
        hibernate:
            ddl-auto: update
        jta:
            log-dir: classpath:jta-logs2
            transaction-manager-id: txManager
        database: h2

    h2:
        console:
            enabled: true
            path: /console
            settings:
                trace: false
                web-allow-others: true

    application:
        name: demo
    thymeleaf:
        cache: false

server:
    port: 80
